name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install calver-auto-release
        run: |
          uv pip install -e ".[test]"

      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest
